config/routes.rb
ScalarmPlatformManager::Application.routes.draw do
  match "platform" => 'platform#index'
  get "platform/index"
  post "platform/synchronize_with_information_service"
  get "platform/synchronize_with_information_service"

  match "platform/install_manager/:manager_uri/:manager_type" => 'platform#install_manager'
  get "platform/install_manager"
  match "platform/start_manager/:manager_uri/:manager_type/:number" => 'platform#start_manager'
  get "platform/start_manager"
  match "platform/stop_manager/:manager_uri/:manager_type/:number" => 'platform#stop_manager'
  get "platform/stop_manager"

  match "platform/delete_manager/:manager_uri" => 'platform#delete_manager'

  match "platform/global_install_manager/:manager_type" => 'platform#global_install_manager'
  get "platform/global_install_manager"
  match "platform/global_start_manager/:manager_type/:number" => 'platform#global_start_manager'
  match "platform/global_stop_manager/:manager_type/:number" => 'platform#global_stop_manager'
  get "platform/global_start_manager"
  get "platform/global_stop_manager"
  
  post "platform/custom_start_managers"

  post "platform/ignore_when_scale" => "platform#ignore_when_scale", :as => :ignore_manager_when_scale

  match "monitoring" => "monitoring#index"
  get "monitoring/index"
  post "monitoring/start_monitoring"
  get "monitoring/monitor"

  match "scaling_rules" => "scaling_rules#index"
  post "scaling_rules/create_new"
  post "scaling_rules/delete_rule"

end

app/controllers/monitoring_controller.rb
require "mongo"

class MonitoringController < ApplicationController
  MONITORING_TABLE_PATTERN = /.*_.*_.*\..*___.*___.*/
  before_filter :authenticate
  before_filter :prepare_db_connection

  def index
    if @monitoring_db != nil
      collections = @monitoring_db.collection_names.select do |collection_name|
        collection_name =~ MonitoringController::MONITORING_TABLE_PATTERN
      end

      @measurements = {}
      collections.each do |collection|
        host_part, metric_part = collection.split(".")

        @measurements[host_part] = [] if not @measurements.has_key? host_part

        @measurements[host_part] << metric_part
      end
      # @measurements = @measurements.sort_by{|host_part, metrics| host_part}

    else
      flash[:error] = "Could not connect to the Monitoring DB"

      redirect_to :controller => "platform", :action => "index"
    end
  end

  def start_monitoring
    params[:action] = :monitor

    redirect_to(params)
  end

  def monitor
    parse_monitoring_options
    @metrics = {}

    params.each do |param_name, param_value|
      next if (param_name =~ MonitoringController::MONITORING_TABLE_PATTERN).nil?

      @metrics[param_name] = measurements_for param_name
      #logger.debug("Metric measurements for #{param_name}: #{@metrics[param_name]}")
    end

    @grouped_metrics = @metrics.keys.group_by do |metric_name|
      splitted = metric_name.split(".")[1].split("___")
      "#{splitted[0]}___#{splitted[2]}"
    end

    #logger.debug("Grouped metrics: #{map_to_string(@grouped_metrics)}")

    @chart_data = {}
    @grouped_metrics.each do |metric_name, metric_list|
      series = []
      metric_list.each do |metric_info|
        splitted = metric_info.split(".")
        series_name = "#{splitted[0]}"
        if splitted[1].split("___")[1] != "NULL"
          series_name += "___#{splitted[1].split("___")[1]}"
        end
        series_data = @metrics[metric_info].map{|t| "[#{t.join(",")}]" }.join(",")

        series << "{ name: '#{series_name}', data: [ #{series_data} ]  }"
      end

      @chart_data[metric_name] = series.join(",")
    end
  end


  private

  def string_to_time(string_date)
    DateTime.strptime(string_date, "%Y-%m-%d %H:%M:%S").to_time
  end

  def measurements_for(metric_name)
    metric_values = @monitoring_db[metric_name].find(date_find_conditions,
                      { :fields => { "_id" => 0, "date" => 1, "value" => 1 } }
                    ).to_a.sort_by{|a| a["data"]}.map{|doc|
                    [ string_to_time(doc["date"]).to_i, doc["value"].to_f ] }

    return [] if metric_values.nil? or metric_values.empty?
    # logger.info(metric_values.map{|x| x[0]}.join(","))

    grouped_values, measurements_from_time_period = [], []

    last_measurement_date = metric_values[0][0]
    metric_values[1..-1].each do |metric_value|
      measurement_date = metric_value[0]

      if measurement_date - last_measurement_date < @time_resolution
        measurements_from_time_period << metric_value[1]
        next
      end

      measurements_from_time_period << metric_value[1]
      grouped_values << calculate_avg_from(last_measurement_date, measurements_from_time_period)
      grouped_values << calculate_avg_from(metric_value[0], measurements_from_time_period)
      last_measurement_date = metric_value[0]
      measurements_from_time_period = []
    end

    if not measurements_from_time_period.empty?
      grouped_values << calculate_avg_from(metric_values[-1][0], measurements_from_time_period)
    end

    grouped_values
  end

  def calculate_avg_from(timestamp, measurements_from_time_period)
    metric_value_sum = measurements_from_time_period.reduce(0, :+)
    metric_value_avg = metric_value_sum / measurements_from_time_period.size

    # logger.info("Sum = #{metric_value_sum} --- Size: #{measurements_from_time_period.size} --- Avg: #{metric_value_avg}")

    [timestamp*1000, metric_value_avg]
  end

  def date_find_conditions
    find_conditions = {}
    if not @monitoring_period_start.nil?
      find_conditions["date"] = { "$gt" => @monitoring_period_start }
    end

    if not @monitoring_period_end.nil?
      if find_conditions["date"]
        find_conditions["date"]["$lte"] = @monitoring_period_end
      else
        find_conditions["date"] = { "$lte" => @monitoring_period_end }
      end
    end

    find_conditions
  end

  def prepare_db_connection
    @config = YAML.load_file(File.join(Rails.root, "config", "platform_manager_config.yml"))
    logger.debug("Monitoring DB URL: #{@config["monitoring_db_url"]}")
    monitoring_db_ip, monitoring_db_port = @config["monitoring_db_url"].split(":")

    begin
      logger.debug("IP: #{monitoring_db_ip} --- Port: #{monitoring_db_port}")
      @monitoring_db = Mongo::Connection.new(monitoring_db_ip, monitoring_db_port.to_i).db(@config["monitoring_db_name"])
      logger.debug("Monitoring DB: #{@monitoring_db}")

      if @config.has_key? "monitoring_db_login"
        auth = @monitoring_db.authenticate(@config["monitoring_db_login"], @config["monitoring_db_password"])
        raise "Could not authenticated" if not auth
      end
    rescue Exception => e
      logger.error("Could not connect to the monitoring db")
      @monitoring_db = nil
    end
  end

  def parse_monitoring_options
    @time_resolution = params[:time_resolution].to_i

    #monitoring period params
    @monitoring_period_start = params[:monitoring_period_start]
    @monitoring_period_start = nil if @monitoring_period_start.blank?
    @monitoring_period_start = "#{@monitoring_period_start} #{params[:monitoring_period_start_time]}"

    @monitoring_period_end = params[:monitoring_period_end]
    @monitoring_period_end = nil if @monitoring_period_end.blank?
    @monitoring_period_end = "#{@monitoring_period_end} #{params[:monitoring_period_end_time]}"

    logger.info("Monitoring time period: #{@monitoring_period_start} - #{@monitoring_period_end}")

    @online_monitoring = params[:online_monitoring]
  end

end

app/helpers/monitoring_helper.rb
module MonitoringHelper

  def time_resolution_options
    [
        ["30 sec", "30"],
        ["1 min", "60"],
        ["30 min", "1800"],
        ["1 h", "3600"],
        ["5 min", "300"]
    ].reverse
  end

  def hour_options
    hours = []

    0.upto(24) do |hour|
      hours << [ "#{hour}:00", "#{hour}:00:00"]
    end

    hours
  end

  def refresh_action
    #action_body = "$.ajax({ '#{monitoring_monitor_path}', "
    #action_body += "data:  "

    #action_body + "});"
    "window.location.href = window.location.href + '&reload=1';"
  end

end

app/views/monitoring/_monitored_host.html.erb
<h3>
  <a href="#">
    Monitored Host IP: <%= monitored_host.gsub("_", ".") %>
  </a>
</h3>
<div>
  <% grouped_measurements = @measurements[monitored_host].group_by{|table_name| table_name.split("___")[0..1].join("___") } %>
  <% grouped_measurements.each do |element_name, tables| %>
    <% element_type, element_id = element_name.split("___") %>
    <h4><%= element_type %> <%= "- #{element_id}" if element_id != "NULL" %> :</h4>

    <% tables.each do |table_name| %>
      <%= check_box_tag "#{monitored_host}.#{table_name}" %>
      <%= table_name.split("___")[-1] %>
      <br/>
    <% end %>
  <% end %>
</div>

app/views/monitoring/_monitoring_chart.html.erb
<div id="chart_container_<%= monitoring_chart %>"></div>

<%= javascript_tag "init_monitoring_chart('#{monitoring_chart}', [ #{@chart_data[monitoring_chart]} ] );" %>

app/views/monitoring/index.html.erb
<section id="main">
  <%= form_tag(monitoring_start_monitoring_path) do %>
    <article>
      <h3>Monitoring options</h3>
      Start date: <%= text_field_tag "monitoring_period_start", Time.now.strftime("%Y-%m-%d") %> -
      Hour: <%= select_tag "monitoring_period_start_time", options_for_select(hour_options) %><br />

      &nbsp;&nbsp;End date: <%= text_field_tag "monitoring_period_end", (Time.now + 1.day).strftime("%Y-%m-%d") %> -
      Hour: <%= select_tag "monitoring_period_end_time", options_for_select(hour_options) %><br />

      Time resolution: <%= select_tag "time_resolution", options_for_select(time_resolution_options) %><br />
    </article>

    <article>
      <h3>Monitored hosts with Node Manager installed</h3>
        <div id="monitored_hosts_accordion">
          <%= render :partial => "monitored_host", :collection => @measurements.keys %>
        </div>
    </article>
    <article>
      <h3>Actions</h3>
      <%= submit_tag "Submit" %>
    </article>
  <% end %>
</section>

<script>
  $(function() {
    $( "#monitoring_period_start" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 3,
      dateFormat: "yy-mm-dd",
      onSelect: function( selectedDate ) {
        $( "#monitoring_period_end" ).datepicker( "option", "minDate", selectedDate );
      }
    });
    $( "#monitoring_period_end" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 3,
      dateFormat: "yy-mm-dd",
      onSelect: function( selectedDate ) {
        $( "#monitoring_period_start" ).datepicker( "option", "maxDate", selectedDate );
      }
    });
  });
</script>

<%= javascript_tag "$( '#monitored_hosts_accordion' ).accordion({ autoHeight: false });" %>
<%= javascript_tag "$( 'input:submit' ).button();" %>

app/views/monitoring/monitor.html.erb
<%=  javascript_include_tag "highcharts" %>

<section id="main">
  <article>
    <h3>Actions</h3>

    <div class="buttons">
      <%= link_to_function "Refresh", refresh_action %>
    </div>
  </article>

  <article>
    <h3>Monitoring charts</h3>

    <%= render :partial => "monitoring_chart", :collection => @chart_data.keys %>
  </article>
</section>

<%= javascript_tag "$( '.buttons a' ).button();" %>