config/routes.rb
ScalarmPlatformManager::Application.routes.draw do
  match "platform" => 'platform#index'
  get "platform/index"
  post "platform/synchronize_with_information_service"
  get "platform/synchronize_with_information_service"

  match "platform/install_manager/:manager_uri/:manager_type" => 'platform#install_manager'
  get "platform/install_manager"
  match "platform/start_manager/:manager_uri/:manager_type/:number" => 'platform#start_manager'
  get "platform/start_manager"
  match "platform/stop_manager/:manager_uri/:manager_type/:number" => 'platform#stop_manager'
  get "platform/stop_manager"

  match "platform/delete_manager/:manager_uri" => 'platform#delete_manager'

  match "platform/global_install_manager/:manager_type" => 'platform#global_install_manager'
  get "platform/global_install_manager"
  match "platform/global_start_manager/:manager_type/:number" => 'platform#global_start_manager'
  match "platform/global_stop_manager/:manager_type/:number" => 'platform#global_stop_manager'
  get "platform/global_start_manager"
  get "platform/global_stop_manager"
  
  post "platform/custom_start_managers"

  post "platform/ignore_when_scale" => "platform#ignore_when_scale", :as => :ignore_manager_when_scale

  match "monitoring" => "monitoring#index"
  get "monitoring/index"
  post "monitoring/start_monitoring"
  get "monitoring/monitor"

  match "scaling_rules" => "scaling_rules#index"
  post "scaling_rules/create_new"
  post "scaling_rules/delete_rule"

end

app/controllers/platform_controller.rb
require "yaml"
require "net/http"

require "information_service"

class PlatformController < ApplicationController
  before_filter :authenticate
  before_filter :load_config

  def index
    @node_managers = NodeManager.all.sort{|a,b| a.uri <=> b.uri}
    @status_information = platform_current_status
  end

  def synchronize_with_information_service
    NodeManager.delete_all

    @information_service.list_of_node_managers.each do |node_manager_desc|
      node_manager_desc = node_manager_desc.split("---")
      manager_uri = node_manager_desc[0]
      manager_registered_at = DateTime.strptime(node_manager_desc[1])

      next if not NodeManager.find_by_uri(manager_uri).nil?

      node_manager = NodeManager.new(:uri => manager_uri, :registered_at => manager_registered_at)
      node_manager.save
    end

    redirect_to :action => :index
  end

  def install_manager
    node_manager = NodeManager.find_by_uri(params[:manager_uri].gsub("_", ".").gsub("-", ":"))
    node_manager.install(params[:manager_type], @config)

    redirect_to :action => :index
  end

  def start_manager
    node_manager = NodeManager.find_by_uri(params[:manager_uri].gsub("_", ".").gsub("-", ":"))
    node_manager.start(params[:manager_type], params[:number], @config)

    redirect_to :action => :index
  end

  def stop_manager
    node_manager = NodeManager.find_by_uri(params[:manager_uri].gsub("_", ".").gsub("-", ":"))
    node_manager.stop(params[:manager_type], params[:number], @config)

    redirect_to :action => :index
  end

  def global_install_manager
    NodeManager.all.each do |node_manager|
      node_manager.install(params[:manager_type], @config)
    end

    redirect_to :action => :index
  end

  def global_start_manager
    NodeManager.all.each do |node_manager|
      node_manager.start(params[:manager_type], params[:number], @config)
    end

    redirect_to :action => :index
  end

  def global_stop_manager
    NodeManager.all.each do |node_manager|
      node_manager.stop(params[:manager_type], params[:number], @config)
    end

    redirect_to :action => :index
  end

  def delete_manager
    node_manager = NodeManager.find_by_uri(params[:manager_uri].gsub("_", ".").gsub("-", ":"))
    node_manager.delete

    redirect_to :action => :index
  end
  
  def custom_start_managers
    experiment_managers_count = params[:experiment_managers_count].to_i
    storage_managers_count = params[:storage_managers_count].to_i
    
    NodeManager.all.each do |node_manager|
      break if (experiment_managers_count <= 0) and (storage_managers_count <= 0)
      
      if experiment_managers_count > 0
        no_managers_to_start = [8, experiment_managers_count].min
        node_manager.start("experiment", no_managers_to_start, @config)
        experiment_managers_count -= no_managers_to_start  
      end
      
      if storage_managers_count > 0
        node_manager.start("storage", 1, @config)
        storage_managers_count -= 1  
      end
    end 
    
    redirect_to :action => :index
  end

  def ignore_when_scale
    # set ignore when applying scaling rule flag for chosen node manager
    node_manager = NodeManager.find(params[:node_manager_id])
    node_manager.ignore = params[:ignore]
    node_manager.save

    redirect_to :action => :index
  end


  private

  def load_config
    @config = YAML::load_file File.join(Rails.root, "config", "platform_manager_config.yml")
    @information_service = InformationService.new(@config)
  end

  def platform_current_status
    status_info = {}
    status_info["node_managers_size"] = @node_managers.size

    experiment_managers_installations = 0
    experiment_managers_instances = 0
    storage_managers_installations = 0

    @node_managers.each do |node_manager|
      experiment_manager_status = node_manager.manager_status("experiment", 8, @config)

      if experiment_manager_status != "not running"
        experiment_managers_installations += 1
        experiment_managers_instances += experiment_manager_status.split(" ")[0].to_i
      end

      status_info[node_manager.uri] = experiment_manager_status

      storage_manager_status = node_manager.manager_status("storage", 1, @config)

      if storage_manager_status != "not running"
        storage_managers_installations += 1
      end

      status_info["storage_#{node_manager.uri}"] = storage_manager_status
    end

    status_info["experiment_managers_installations"] = experiment_managers_installations
    status_info["experiment_managers_instances"] = experiment_managers_instances

    status_info["storage_managers_installations"] = storage_managers_installations

    status_info["storage_db_config_services"] = @information_service.list_of_db_configs
    status_info["storage_db_instances"] = @information_service.list_of_db_instances

    return status_info
  end

end

app/helpers/platform_helper.rb
module PlatformHelper

  def manager_installation_options
    [
        ["Experiment Manager", "experiment"],
        ["Storage Manager", "storage"],
        ["Simulation Manager", "simulation"]
    ]
  end

  def global_action_options
    [
        ["start", "start"],
        ["stop", "stop"]
    ]
  end

  def manager_type_options
    [
        ["Experiment Manager", "experiment"],
        ["Storage Manager - database instance", "storage_db_instance"],
        ["Simulation Manager", "simulation"],
    ]
  end

  def local_manager_type_options
    [
        ["Experiment Manager", "experiment"],
        ["Storage Manager - config service", "storage_db_config"],
        ["Storage Manager - database instance", "storage_db_instance"],
        ["Storage Manager - router", "storage_db_router"],
        ["Simulation Manager", "simulation"],
    ]
  end
end

app/views/platform/_node_manager.html.erb
<h3>
	<a href="#">
	  Node Manager IP: <%= node_manager.uri %>
      <% if node_manager.ignore %>
        - this manager will be ignored when scaling
      <% else %>
        - this manager will be used when scaling
      <% end %>
	</a>
</h3>

<div style="min-height: 200px;" id="manager_<%= node_manager.uri_to_request %>">

  <article>
    <%= content_tag :h3, "Information" %>

    <%= content_tag :p, "Experiment Manager: #{@status_information[node_manager.uri]}" %>

    <p>
      Storage Manager:
      <% if @status_information["storage_db_config_services"].include? node_manager.uri.split(":").first %>
        Config service is running
      <% elsif @status_information["storage_db_instances"].include? node_manager.uri.split(":").first %>
        DB instance is running
      <% else %>
        not running
      <% end %>
    </p>
  </article>

  <article>
    <%= content_tag :h3, "Actions" %>

    <div class="buttons">
      <div>
        <%= select_tag "install_local_manager_type", options_for_select(manager_installation_options) %>
        <%= link_to_function "Install", "window.executeLocalInstallation('#{platform_install_manager_path}', '#{node_manager.uri_to_request}');" %>
      </div>

      <div>
        <span>Execute</span>
        <%= select_tag "local_action", options_for_select(global_action_options) %>
        <span>of</span>
        <%= select_tag "local_manager_type", options_for_select(local_manager_type_options) %>
        <%= link_to_function "Execute", "window.executeLocal('#{platform_start_manager_path}', '#{platform_stop_manager_path}', '#{node_manager.uri_to_request}');" %>
      </div>

      <%= link_to "Delete node manager from the view", "/platform/delete_manager/#{node_manager.uri_to_request}" %>

      <% if node_manager.ignore %>
        <%= link_to "Include when scaling", ignore_manager_when_scale_path(:node_manager_id => node_manager.id, :ignore => false), :method => :post %>
      <% else %>
        <%= link_to "Exclude when scaling", ignore_manager_when_scale_path(:node_manager_id => node_manager.id, :ignore => true), :method => :post %>
      <% end %>

      <%= image_tag "spinner.gif", :class => "spinner", :style => "display: none;" %>
    </div>
  </article>

</div>

app/views/platform/_platform_information.html.erb
<article>
  <%= content_tag :h3, "Platform Information" %>

  <%= content_tag :p, "Currently you have #{@status_information["node_managers_size"]} Node Managers registered." %>

  <%= content_tag :p, "#{@status_information["experiment_managers_installations"]} of them are running
  #{@status_information["experiment_managers_instances"]} instances of Scalarm Experiment Manager."  %>

  <p>
    <%= content_tag :h4, "Storage db config services" %>
    <ul>
      <% @status_information["storage_db_config_services"].each do |config_ip| %>
        <%= content_tag :li, config_ip %>
      <% end %>
    </ul>
  </p>

  <p>
    <%= content_tag :h4, "Storage db instances" %>
    <ul>
      <% @status_information["storage_db_instances"].each do |db_ip| %>
        <%= content_tag :li, db_ip %>
      <% end %>
    </ul>
  </p>
</article>

app/views/platform/index.html.erb
<section id="main">

  <%= render :partial => "platform_information" %>

  <article>
    <h3>Global actions</h3>

    <div class="buttons">
      <%= link_to "Synchronize with the Information Service", platform_synchronize_with_information_service_path %>
      <%= link_to "Monitoring panel", monitoring_index_path %>

      <div>
        Install on all nodes
        <%= select_tag "install_manager_type", options_for_select(manager_installation_options) %>
        <%= link_to_function "Install", "window.executeInstallation('#{platform_global_install_manager_path}');" %>
      </div>

      <div>
        <span>Execute</span>
        <%= select_tag "global_action", options_for_select(global_action_options) %>
        <span>of</span>
        <%= select_tag "manager_type", options_for_select(manager_type_options) %>
        <span>on all nodes</span>
        <%= link_to_function "Execute", "window.execute('#{platform_global_start_manager_path}', '#{platform_global_stop_manager_path}');" %>
      </div>

      <div class="buttonset">
      	<%= form_tag(platform_custom_start_managers_path) do -%>
      		Number of Experiment Managers to start:
      		<%= text_field_tag "experiment_managers_count" %><br/>
      		Number of Storage Managers to start:
      		<%= text_field_tag "storage_managers_count" %><br/>
      		<%= submit_tag "Start" %>
      	<% end %>
      </div>
    </div>

  </article>

  <article>
    <h3>Registered Node Managers</h3>
    <div id="node_managers_accordion">
      <%= render :partial => "node_manager", :collection => @node_managers %>
    </div>

    <%= javascript_tag "$(document).ready(function() { $( '#node_managers_accordion' ).accordion({ autoHeight: false, collapsible: true }); })" %>
  </article>
</section>

<%= javascript_tag "$(document).ready(function() { $('.buttons a').button(); $( '.buttonset' ).buttonset();
                    $('.buttons a, .buttonset a').click(function() { $(this).next('.spinner').show() })})" %>